### ISSUE TITLE
Snapshot image not visible on myopenhab app on iPhone

### ISSUE THREAD

**Issue by cbugeja** [Skinah/IpCamera#32] opened 2019-07-11 22:43 UTC
The snapshot image does not show on the iPone app of myopenhab.
Meanwhile, it shows and refreshes perfectly on the Android apps (even in the beta app).

I am using an Avigilon camera with ONVIF capabilities through the <"ONVIF" Generic IP camera with ONVIF support> thing.

![android](https://user-images.githubusercontent.com/327314/61090125-b64d7280-a43d-11e9-8abe-2e14ab184205.jpg)
![iPhone](https://user-images.githubusercontent.com/327314/61090126-b64d7280-a43d-11e9-8f05-1ab49e89b208.jpg)

**Comment by Skinah** [comment] 2019-07-12 03:23
This is not a bug in the binding, you should raise an issue on the Openhab ios and android app pages.

IMAGE = good for android app.
WEBVIEW = good for ios app.

Sadly you have to implement both as each app has issues with the other type.

To see an example of using webview see this link, it works for video streams and snapshots..

https://github.com/openhab/openhab1-addons/wiki/Foscam-IP-Cameras#displaying-streaming-video-in-sitemap

On ios the HLS streaming works great.

**Comment by cbugeja** [comment] 2019-07-12 10:20
Thanks a lot for the reply.
In my case, an image with a normal url (or a link to an image on the webserver) works fine on both android and iOS... only this image with the camera snapshot item does not work on iOS. (webview, even text only, is also only working on android and not on iOS)

I will read through the suggested link. 

Will also try to implement the HLS streaming and see how it goes.

**Comment by Skinah** [comment] 2019-07-15 11:46
You can use the binding to provide a JPG via a url if that way works better, the url is this 
http://192.168.1.2:54321/ipcamera.jpg
By turning off the Image channel from updating and using this url instead I find halves the CPU used by the binding and is worth doing.

I wrote a how to guide here which you may find helpful.

https://community.openhab.org/t/ip-camera-how-to-clickable-thumbnail-overview-in-sitemaps-that-opens-up-to-a-larger-view/77990

I will close this issue, but feel free to reopen it if you feel the binding needs something changed or looked at. If the binding does not work for a way that works for any normal url let me know as I consider it a bug, but I suspect the issue is the openhab framework as after the binding sends the picture to the image channel it is then the responsibility of Openhabs framework to handle the rest. An issue at the Openhab github to report it should be done in that case.

**Closed by Skinah** 2019-07-15 11:46 UTC
