### ISSUE TITLE
Incorrect login data locks Foscams

### ISSUE THREAD

**Issue by roben** [Skinah/IpCamera#11] opened 2018-08-26 09:51 UTC
I had really serious issues after hard-resetting my Foscam C1. Either it did not let me set a new password or it prompted me for a login (default admin/empty should have worked) but did not let me in. Only after setting it up with Wifi instead of wired connection and thus with a different IP it worked fine again. I think it is because the Camera binding tries to access the camera repeatedly using incorrect credentials which causes the camera to block any further logins. Maybe the binding should stop connecting after login failures for some time.

I set up a different login on my Wifi based attempt and after switching back to wired the camera was locked again. After disabling the OH things and restarting the camera I was able to login again.

This is not solid evidence, but it sounds reasonable to me ;)

**Comment by Skinah** [comment] 2018-09-02 04:36
Hikvision cameras do the same thing, they also can have the feature disabled. If I was to add the ability for
The binding to stop connecting, how would it know if it is caused by a bad network cable or a temporary issue? It would stop other
Cameras from auto working again after a temporary issue goes
Away. Perhaps this could be an option that could be turned on and off, or perhaps we take the stance that people just need to get the login details correct? Any feedback would be great.

**Comment by Skinah** [comment] 2018-09-03 08:29
After thinking about this some more, it is possible to detect if the camera replies with a 50X message as some cameras will reply to say it is a login issue. I'll mark this as a future feature to add.

**Comment by roben** [comment] 2018-09-03 19:12
Yeah I know, it's nothing with a simple solution. Maybe just reduce the polling interval after connection failures so that the cameras don't lock up. But I don't even know if this helps at all or if the cameras simply count subsequent login failures no matter how much time passed between them.
The quickest fix would be a simple warning in the documentation, though ;)

**Comment by Skinah** [comment] 2019-02-08 06:41
Readme updated with a note on this. Happy to look at automating it if you can let me know if the camera replies with a 50x http error code. The binding will list this in the logs when you enabled TRACE logging. Closing for now unless you wish to re-open with this info...

**Closed by Skinah** 2019-02-08 06:41 UTC
Labels: enhancement
