### ISSUE TITLE
Get Instar camera to work

### ISSUE THREAD

**Issue by phil100vol** [Skinah/IpCamera#29] opened 2019-06-15 20:39 UTC
Hey,

thanks for the interesting binding. Since a couple of days I am trying to get my Instar 8015 POE working. The binding is able to connect to the camera but when I try an item (in my case 'tilt') nothing moves. I am also not able to get an image from the camera.
After changing the tilt.state by a slider item I can see the new value in the log file but the camera didn`t move a bit

I checked the IP, Port, activated ONVIF protocol (at the camera).

Hope some can help me :-(

Thanks 
Phil

**Comment by Skinah** [comment] 2019-06-15 22:12
The onvif port in the binding needs to be 8080 to match what the default port is in the cameras setup. If that does not fix it, you need to look at the logs in debug mode as shown in the readme file. Once posting the log output I can help further.

**Comment by mpolinowski** [comment] 2019-06-16 09:37
Hi Phil,

we uploaded an early version of our tutorial on how to use @Skinah camera binding with our HD/Full HD camera models. There are still missing pieces - but should already allow you to get the live video, control the PTZ function and set the alarm.


https://wiki.instar.com/Advanced_User/OpenHAB_IP_Camera_Binding/


Mike

**Comment by phil100vol** [comment] 2019-06-16 17:08
hey,

@Skinah Onvif port is configured for the camera and at the binding
@mpolinowski I tried your tutorial step by step. First I got an error for the snapshot_url:
`[ERROR] [ing.ipcamera.handler.IpCameraHandler] - Camera failed to report a valid Snaphot URL, try over-riding the Snapshot URL auto detection by entering a known URL.`

I 'fixed' it by using a fake urlhttp://192.168...:888. Afterwards the thing switched to green = online. I was able to create the channels and itemas (pan and snapshot) but the same problem occurred. The state changes or refreshes but the camera didn`t move or showed a snapshot.

> Snapshot from camera
No image is currently present

Thanks Phil

**Comment by Skinah** [comment] 2019-06-17 00:27
As mentioned you need to enable the debug log
Output which is explained in the readme file. You do not see everything that is going on unless you do this. Without the log I can only make guesses.
Your issue will be from ONVIF not connecting or perhaps the user/pass does not match or the user does not have enough privileges. Without onvif working the PTZ features will not work but the rest of the binding will if you manually provide the correct urls.

No onvif means no movement.

**Comment by mpolinowski** [comment] 2019-06-17 07:28
@phil100vol can you try overwriting the default URLs ?

![openhab](https://user-images.githubusercontent.com/18694428/59585720-bc3c8600-9113-11e9-9137-cce9f8c141a9.png)

I changed those in the beginning but did not think that it was necessary to do so. But I just noticed that adding a IN-8015 FHD without changing those URLs also did not work (@Skinah I don't have the debug log active right now - only noticed that the snapshot did not show up. Everything works now that I added them). But it only affected the Snapshot - PTZ, activating the audio alarm and setting its sensitivity works without issues.

**Comment by mpolinowski** [comment] 2019-06-17 08:08
The debug log:

![openhab](https://user-images.githubusercontent.com/18694428/59588353-fd379900-9119-11e9-9fda-7778a8a34244.png)



https://gist.github.com/mpolinowski/50d7411f876b9ad1cd1b288d10964876

**Comment by Skinah** [comment] 2019-06-17 10:34
Mike that log shows it was possibly not setup as INSTAR due to the 404 urls belong to another brand.
Also I need the log from when the camera is connecting, that was from after it had already connected and was fetching snapshots.

If it has issues connecting via onvif it only logs the reason why in debug or traces modes. The log was correct just from after the camera had already passed
Onvif connecting.

**Comment by mpolinowski** [comment] 2019-06-17 11:44
Hi Matt,

I cleared the logs, re-added the 8015 and uploaded the new log and event file:

https://gist.github.com/mpolinowski/eda47b9d611b47c74a3e736717c39137

https://gist.github.com/mpolinowski/3f26dd32bc55078ef4e11af35a5119ee


There are two cameras added - a 9020 (on IP *.118) where I added the correct snapshot path and that works and the  8015 (INSTARHDIPCameraWithONVIFAndAPISupport on IP *.116). I am able to activate the audio alarm for the 8015 and set the sensitivity - but there is now snapshot.


It works once I set `SNAPSHOT_URL_OVERRIDE` to `/tmpfs/auto.jpg`.

**Comment by phil100vol** [comment] 2019-06-17 14:44
hey,

@mpolinowski I changed my urls to your mentioned preset -> same issue
afterwards I enabled the trace mode 'log:set TRACE ...'
@Skinah 
`16:37:26.315 [DEBUG] [ding.ipcamera.handler.IpCameraHandler] - Sending camera GET: http://192.168.222.101:80/tmps/auto.jpg
16:37:26.328 [TRACE] [.ipcamera.internal.MyNettyAuthHandler] - MyNettyAuthHandler is now setup for 	GET:/tmps/auto.jpg
16:37:26.331 [DEBUG] [ding.ipcamera.handler.IpCameraHandler] - Have re-opened  the closed channel:0 	GET:/tmps/auto.jpg
16:37:26.334 [DEBUG] [ding.ipcamera.handler.IpCameraHandler] - Sending camera GET: http://192.168.222.101:80/cgi-bin/hi3510/param.cgi?cmd=getaudioalarmattr
16:37:26.341 [TRACE] [ding.ipcamera.handler.IpCameraHandler] - DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Cache-Control: no-cache,no-store
Content-Type: text/plain
Content-Length: 35
Connection: keep-alive
16:37:26.346 [TRACE] [.ipcamera.internal.MyNettyAuthHandler] - MyNettyAuthHandler is now setup for 	GET:/cgi-bin/hi3510/param.cgi?cmd=getaudioalarmattr
16:37:26.347 [TRACE] [ding.ipcamera.handler.IpCameraHandler] - DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 35, cap: 35/35, unwrapped: PooledUnsafeDirectByteBuf(ridx: 197, widx: 197, cap: 1024)), decoderResult: success)
16:37:26.349 [DEBUG] [ding.ipcamera.handler.IpCameraHandler] - Have re-opened  the closed channel:2 	GET:/cgi-bin/hi3510/param.cgi?cmd=getaudioalarmattr
16:37:26.353 [DEBUG] [ding.ipcamera.handler.IpCameraHandler] - Sending camera GET: http://192.168.222.101:80/cgi-bin/hi3510/param.cgi?cmd=getmdattr
16:37:26.358 [TRACE] [ding.ipcamera.handler.IpCameraHandler] - DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
Server: Ipcam
Access-Control-Allow-Origin: *
Cache-Control: no-cache,no-store
Content-Type: text/html
Connection: close
Content-Length: 58
16:37:26.361 [TRACE] [ding.ipcamera.handler.IpCameraHandler] - HTTP Result back from camera is 	:Error 404: Not Found
File not found:
16:37:26.366 [TRACE] [.ipcamera.internal.MyNettyAuthHandler] - MyNettyAuthHandler is now setup for 	GET:/cgi-bin/hi3510/param.cgi?cmd=getmdattr
16:37:26.373 [TRACE] [ding.ipcamera.handler.IpCameraHandler] - DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 58, cap: 58/58, unwrapped: PooledUnsafeDirectByteBuf(ridx: 221, widx: 221, cap: 1024)), decoderResult: success)
16:37:26.376 [DEBUG] [ding.ipcamera.handler.IpCameraHandler] - commonCameraHandler closed channel:0 	URL:/tmps/auto.jpg
16:37:26.377 [TRACE] [ding.ipcamera.handler.IpCameraHandler] - HTTP Result back from camera is 	:var aa_enable="0";
var aa_value="50";
var aa_time="0";
:
16:37:26.380 [DEBUG] [ding.ipcamera.handler.IpCameraHandler] - Have re-opened  the closed channel:3 	GET:/cgi-bin/hi3510/param.cgi?cmd=getmdattr
16:37:26.382 [DEBUG] [ding.ipcamera.handler.IpCameraHandler] - commonCameraHandler closed channel:2 	URL:/cgi-bin/hi3510/param.cgi?cmd=getaudioalarmattr
16:37:26.392 [TRACE] [ding.ipcamera.handler.IpCameraHandler] - DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
Server: Ipcam
Access-Control-Allow-Origin: *
Cache-Control: no-cache,no-store
Content-Type: text/html
Connection: close
Content-Length: 544
16:37:26.397 [TRACE] [ding.ipcamera.handler.IpCameraHandler] - DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 544, cap: 544/544, unwrapped: PooledUnsafeDirectByteBuf(ridx: 708, widx: 708, cap: 1024)), decoderResult: success)
16:37:26.400 [TRACE] [ding.ipcamera.handler.IpCameraHandler] - HTTP Result back from camera is 	:var m1_enable="0";
var m1_x="0";
var m1_y="0";
var m1_w="1920";
var m1_h="1080";
var m1_sensitivity="50";
var m1_threshold="0";
var m2_enable="0";
var m2_x="1680";
var m2_y="0";
var m2_w="240";
var m2_h="240";
var m2_sensitivity="50";
var m2_threshold="0";
var m3_enable="0";
var m3_x="0";
var m3_y="840";
var m3_w="240";
var m3_h="240";
var m3_sensitivity="50";
var m3_threshold="0";
var m4_enable="0";
var m4_x="1680";
var m4_y="840";
var m4_w="240";
var m4_h="240";
var m4_sensitivity="50";
var m4_threshold="0";
:
16:37:26.406 [DEBUG] [ding.ipcamera.handler.IpCameraHandler] - commonCameraHandler closed channel:3 	URL:/cgi-bin/hi3510/param.cgi?cmd=getmdattr
`

This part repeats after roundabout 2 secs.

**Comment by Skinah** [comment] 2019-06-17 23:42
Phil
To stop the event log getting flooded with snapshot info, see thereadme for how to use a filter.
To stop the openhab.log you need to change it back to INFO log level.

Mike
Does one of the two cameras work with ptz? As only one comes up with a soap error which appears to be when one of the cameras is asked for the rtsp stream url.

One thing to try is moving all three controls, move pan, tilt and zoom as I have seen a camera not move until all three had been touched. It could be that when the camera is asked its current location it may reply with null or undefined until all three have been set for the first time.

**Comment by phil100vol** [comment] 2019-06-20 20:20
@Skinah 
regarding PTZ: I tried changing all three values (tilt, pan and zoom). Not one of them is undefined or null. Unfortunately the camera still dont move 
All in DEBUG mode:
`[ome.event.ItemCommandEvent] - Item 'panpan' received command 45
[nt.ItemStatePredictedEvent] - panpan predicted to become 45
[vent.ItemStateChangedEvent] - panpan changed from 61 to 45`
Same for zoom and pan.

Logs from initializing the camera again, using @mpolinowski mentioned URLs:

`2019-06-20 22:17:06.128 [hingStatusInfoChangedEvent] - 'ipcamera:INSTAR:cd45f213' changed from UNINITIALIZED to INITIALIZING

2019-06-20 22:17:06.127 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - initialize() called.

2019-06-20 22:17:07.152 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - About to connect to the IP Camera using the ONVIF PORT at IP:192.168.222.101:8080

2019-06-20 22:17:07.161 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Can not connect with ONVIF to the camera at 192.168.222.101, check the ONVIF_PORT is correct. Fault was java.net.ConnectException: Host not available.

2019-06-20 22:17:07.165 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera GET: http://192.168.222.101:80/tmpfs/auto.jpg

2019-06-20 22:17:07.179 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Have  opened  a  brand NEW channel:0 	GET:/tmpfs/auto.jpg

2019-06-20 22:17:07.196 [DEBUG] [ipcamera.internal.MyNettyAuthHandler] - 401: Mark as closing, the  channel:0 	GET:/tmpfs/auto.jpg

2019-06-20 22:17:07.201 [DEBUG] [ipcamera.internal.MyNettyAuthHandler] - Setting up the camera to use Basic Auth and resending last request with correct auth.

2019-06-20 22:17:07.205 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Setting up the BASIC auth now, this should only happen once.

2019-06-20 22:17:07.205 [hingStatusInfoChangedEvent] - 'ipcamera:INSTAR:cd45f213' changed from INITIALIZING to ONLINE

2019-06-20 22:17:07.199 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - IP Camera at 192.168.222.101:80 is now online.

2019-06-20 22:17:07.210 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera GET: http://192.168.222.101:80/tmpfs/auto.jpg

2019-06-20 22:17:07.232 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Have  opened  a  brand NEW channel:1 	GET:/tmpfs/auto.jpg

2019-06-20 22:17:07.239 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - commonCameraHandler closed channel:0 	URL:/tmpfs/auto.jpg

2019-06-20 22:17:07.320 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Snapshot recieved: Binding will now close the channel.

2019-06-20 22:17:07.324 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - commonCameraHandler closed channel:1 	URL:/tmpfs/auto.jpg

2019-06-20 22:17:14.189 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera GET: http://192.168.222.101:80/tmpfs/auto.jpg

2019-06-20 22:17:14.198 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Have re-opened  the closed channel:0 	GET:/tmpfs/auto.jpg

2019-06-20 22:17:14.200 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera GET: http://192.168.222.101:80/cgi-bin/hi3510/param.cgi?cmd=getaudioalarmattr

2019-06-20 22:17:14.208 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Have  opened  a  brand NEW channel:2 	GET:/cgi-bin/hi3510/param.cgi?cmd=getaudioalarmattr

2019-06-20 22:17:14.211 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera GET: http://192.168.222.101:80/cgi-bin/hi3510/param.cgi?cmd=getmdattr

2019-06-20 22:17:14.228 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Snapshot recieved: Binding will now close the channel.`

ONVIF Port of the camera is 8080 an the protocol is activated...

**Comment by Skinah** [comment] 2019-06-21 03:25
This is the cause, but why I will have to look into this some more...

Fault was java.net.ConnectException: Host not available.

As mentioned all the features should work except the PTZ movements and it is a ONVIF connection issue.

**Comment by Skinah** [comment] 2019-08-03 03:15
I have made some changes for PTZ and also added new features for Instar cameras the last few days, can you update the binding and give it a try please?

**Comment by mpolinowski** [comment] 2019-08-05 13:32
@phil100vol

I had to reinstall OpenHAB, went through my tutorial (linked above) and noticed that I left one step out - but you probably caught that.

The FFMPEG Output path needs to be created and it's owner changed to `openhab:openhab` so that OpenHAB can use it and you can get your camera's snapshot.

![openhab](https://user-images.githubusercontent.com/18694428/62468050-aec48380-b7c7-11e9-8257-e2b9b4b5bccd.png)

I only have issues using the PTZ function with the updated binding.

**Comment by phil100vol** [comment] 2019-08-06 14:09
Hey,

@mpolinowski 
I didn't reinstall whole OpenHab - just the binding. After I followed your tutorial I am able to see the snapshots (with refresh) at my sitemap and in the control field of PaperUI. I am talking about PC sitemap (browser). I cant see anything at my IPhone. There I am using the OpenHab App and the field for snapshots at the sitemap remains blank even if the sitemap at my PC isn't blank. I also tried the IPhone browser -same issue.

@Skinah 
Still I cant use PTZ. I can create and link some PTZ items and change values but nothing moves.

**Comment by Skinah** [comment] 2019-12-26 11:12
Hi @phil100vol ,
Today I uploaded two new versions which use a new ONVIF library, can you test to see if your PTZ issue is now solved?
If you have ONVIF authentication disabled you need to use a different jar to if it is enabled. On my setup I had to disable the onvif credentials for it to connect and then I can move the camera. One of them should work.

**Comment by phil100vol** [comment] 2019-12-29 11:52
@Skinah I am not at home for a couple of days. I will give it a try when I am home again.

**Comment by Skinah** [comment] 2020-01-01 05:48
No problem, I will close this issue for now, feel free to reopen it again if there is an issue. BTW I added the ability to recall Onvif presets with the binding and this is working great with Instar cameras, see the bindings readme file for an example on how to use it. I found I needed to disable the Onvif authentication for it to work but try it with it enabled first as it may be an error on my end here. Look forward to hearing back if it works for you.

**Comment by phil100vol** [comment] 2020-01-05 21:22
Hey @Skinah 

still nothing moves :-(
I used the latest version from 04. January of your binding .jar

**My Instar settings:**
I tried "Activate authentication" Yes and No

![grafik](https://user-images.githubusercontent.com/47931182/71786075-ec903700-3007-11ea-83b0-0fff268bc4ef.png)

**My Openhab settings**
I tried an "INSTAR HD IP ..." & "ONVIF Generic IP ..." with the same values:

![2020-01-05_22-18](https://user-images.githubusercontent.com/47931182/71786228-7096ee80-3009-11ea-952a-f3e8f9be83ed.png)

I am able to see a snapshot and get a connection to the camera, but when I change some pan or tilt values, still nothing moves

> 2020-01-05 22:06:27.741 [hingStatusInfoChangedEvent] - 'ipcamera:INSTAR:a3f64e05' changed from INITIALIZING to ONLINE
2020-01-05 22:06:27.745 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - IP Camera at 192.168.222.101 is now online.
2020-01-05 22:06:28.173 [hingStatusInfoChangedEvent] - 'ipcamera:ONVIF:59ed7d19' changed from INITIALIZING to ONLINE
2020-01-05 22:06:28.177 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - IP Camera at 192.168.222.101 is now online.
2020-01-05 22:06:33.925 [ome.event.ItemCommandEvent] - Item 'INSTARHDIPCameraWithONVIFAndAPISupport_Pan' received command 24
2020-01-05 22:06:33.935 [nt.ItemStatePredictedEvent] - INSTARHDIPCameraWithONVIFAndAPISupport_Pan predicted to become 24
2020-01-05 22:06:33.955 [vent.ItemStateChangedEvent] - INSTARHDIPCameraWithONVIFAndAPISupport_Pan changed from 90 to 24
2020-01-05 22:06:35.765 [ome.event.ItemCommandEvent] - Item 'INSTARHDIPCameraWithONVIFAndAPISupport_Tilt' received command 12
2020-01-05 22:06:35.773 [nt.ItemStatePredictedEvent] - INSTARHDIPCameraWithONVIFAndAPISupport_Tilt predicted to become 12
2020-01-05 22:06:35.790 [vent.ItemStateChangedEvent] - INSTARHDIPCameraWithONVIFAndAPISupport_Tilt changed from 42 to 12
2020-01-05 22:06:37.171 [ome.event.ItemCommandEvent] - Item 'ONVIFGenericIPCameraWithONVIFSupport_Pan' received command 42

**Comment by Skinah** [comment] 2020-01-09 11:42
What firmware are you using? Instar released a new one with Onvif changes a few weeks back and that is the one I have working here. I simply setup some preset locations with Onvif device manager and test they work in that program and then I tell Openhab to move the camera using the gotoPreset channel. BTW Instar released MQTT features just recently, not sure if you can move the camera with MQTT but it is also worth a look.

**Comment by phil100vol** [comment] 2020-01-10 22:04
I just updated to firmware 4.1.2.46 and Web Ui 2.4(262). I tried your bindung another time and when I use ONVIF Thing I am able to pan and tilt the camera (the strange behavior I will explain next). When I use the INSTAR Thing nothing moves.

The strange behavior is that the camera just moves to extreme values:
a pan value below 50% let move the camera to the most left position and a value above 50% to the most right positron -> same with tilt (max up or max down)  ... no points in between are possible

I cant try MQTT because I havent any tab to enable MQTT - Its just not shown in my GUI :-/
I used this picture to navigate to MQTT settings but I cant see anything:

[https://wiki.instar.de/Web_User_Interface/1080p_Serie/Netzwerk/MQTT/](url)

Regarding the last point I will contact INSTAR support - or do you have an idea?

**Comment by Skinah** [comment] 2020-01-11 01:01
Re: not moving when instar thingtype, please triple check for typos my guess is you did not replace something from onvif to instar or the UID across. It works here and the exact same code is used for both thing types.

RE: moving to the extremes, change to using the PRESET method as covered in the readme, it works here and is easier to use in rules as it is a single command.

Last point: I believe it is a different firmware that is newer than the one you have now and is an OPEN BETA. Check there webpages for where to download it before contacting them. I have not tried it so i am not 100% sure about it.

**Comment by mpolinowski** [comment] 2020-01-11 10:00
@phil100vol 

Just send an email to support at instar dot de and tell them that you need the MQTT firmware for your camera model. 

Though, as we did not receive any negative response yet, I assume that the firmware will be pushed to the auto-update very soon.

**Comment by phil100vol** [comment] 2020-01-11 21:41
@Skinah 
Thank you for your patience and help. It works and I am able to use INSTAR thingtype and can use the presets to move.

@mpolinowski 
I will send an email to test MQTT as well - thanks for the hint. I thought its the stable firmware because at their InstarWiki they show the mentioned picture with MQTT tab.

**Closed** 2020-01-14 01:56 UTC
